project:
  type: book

lang: es

book:
  title: Not used
  author: Not used
  #date: "10/4/2022"
  chapters:
    - index.qmd
    - Bit1.qmd
    - Bit2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    classoption: ["onepage", "openany"]
    template-partials:
      - "before-body.tex"
      - "_titlepage.tex" 
    include-in-header: 
      - "in-header.tex"
    toc: true
    lof: true
    lot: true

editor: source

