project:
  type: book

lang: es

book:
  title: Not used
  author: Not used
  #date: "10/4/2022"
  chapters:
    - index.qmd
    - Bit1.qmd
    - Bit2.qmd
    - Bit3.qmd
    #- Bit4.qmd
    - Referencias.qmd

bibliography: Referencias.bib
csl: apa.csl
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    classoption: ["onepage", "openany"]
    template-partials:
      - "before-body.tex"
      - "_titlepage.tex" 
    include-in-header: 
      - "in-header.tex"
    toc: true
    lof: true
    lot: true
    fig-pos: 'H'
    fig-cap-location: top
    tbl-cap-location: top
editor: source

geometry:
  - left=.75in
  - right=.75in
  - textwidth=4.5in
  - marginparsep=.25in
  - marginparwidth=2.25in

from: markdown+tex_math_single_backslash
